# Generated by Django 5.0.4 on 2024-04-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_size_alter_category_options_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='рейтинг'),
        ),
    ]
