# Generated by Django 5.0.4 on 2024-05-17 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_review_product'),
        ('user', '0002_alter_profie_options_cart_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='size_cart_product', to='product.size', verbose_name='размер'),
            preserve_default=False,
        ),
    ]
